name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.6
  intl: ^0.19.0
  firebase_core: ^2.25.5
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
